name: Check pull request
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm i
      - name: Check lint
        run: npm run lint
      - name: Check ts
        run: npm run typecheck
      - name: Check format
        run: npm run format
